import { useEffect, useMemo, useState } from "react";
import { createEvent, createGroupChannel, createProject, createTask, getPeople } from "../Kanbas/teamflowClient";
import { CURRENT_USER, MEMBERS, PROJECTS } from "./data";
import type { CreationMode } from "./App";
const field = "w-full rounded-xl px-3 py-2.5 text-[13px] outline-none border border-[#EAECF0] focus:border-[#7C5CFC]";
const Label = ({ children }: { children: React.ReactNode }) => <label className="block text-[11px] font-semibold uppercase tracking-wide mb-1.5 text-[#6B7280]">{children}</label>;
export default function CreateModal({ mode, onClose, onSaved, initialProjectId = "", initialStatus = "BACKLOG" }: { initialProjectId?: string; initialStatus?: string; mode: CreationMode; onClose: () => void; onSaved: () => Promise<void> }) {
 const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [projectId,setProjectId]=useState(initialProjectId); const [assigneeId,setAssigneeId]=useState(""); const [status,setStatus]=useState(initialStatus); const [priority,setPriority]=useState("MEDIUM"); const [startsAt,setStartsAt]=useState(""); const [endsAt,setEndsAt]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [people,setPeople]=useState<any[]>([]); const [query,setQuery]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const members=Object.values(MEMBERS);
 useEffect(()=>{ if(!projectId&&PROJECTS[0])setProjectId(PROJECTS[0].id); if(!assigneeId&&members[0])setAssigneeId(members[0].id); },[projectId,assigneeId,members.length]);
 useEffect(()=>{ if(mode==="groupChat")getPeople().then(setPeople).catch(()=>setError("Could not load teammates.")); },[mode]);
 const chooser=mode==="groupChat"?people.filter(p=>p._id!==CURRENT_USER.id):members.filter(p=>p.id!==CURRENT_USER.id); const id=(p:any)=>p._id||p.id; const name=(p:any)=>p.name||`${p.firstName} ${p.lastName}`; const visible=useMemo(()=>chooser.filter(p=>!selected.includes(id(p))&&name(p).toLowerCase().includes(query.toLowerCase())),[chooser,selected,query]);
 const heading=mode==="event"?"Send meeting invitation":mode==="groupChat"?"Create group chat":mode==="task"?"Create task":mode==="project"?"Start a new project":"Create";
 const save=async()=>{try{setSaving(true);setError(""); if(mode==="task")await createTask({title,description,projectId,assigneeId,status,priority,dueDate:startsAt||undefined}); if(mode==="project")await createProject({name:title,description,dueDate:startsAt||undefined}); if(mode==="event"){if(!selected.length)throw new Error("Choose at least one attendee.");const r=await createEvent({title,description,projectId,startsAt,endsAt:endsAt||undefined,attendeeIds:selected});window.alert(`Invitation sent to ${r.invitationsSent} attendee${r.invitationsSent===1?"":"s"}. It will appear on their Calendar after acceptance.`);} if(mode==="groupChat"){if(!title||!selected.length)throw new Error("Add a channel name and at least one teammate.");await createGroupChannel(title,selected);} await onSaved();onClose();}catch(e:any){setError(e?.response?.data?.message||e.message||"Could not save.");}finally{setSaving(false);}};
 const Picker=()=> <div><Label>{mode==="event"?"Invite attendees":"Add teammates"}</Label><div className="min-h-[44px] flex flex-wrap gap-1.5 p-2 rounded-xl border border-[#EAECF0]">{selected.map(x=>{const p=chooser.find(q=>id(q)===x);return <span key={x} className="inline-flex gap-1 px-2 py-1 rounded-lg bg-[#EEE9FF] text-[#6545E8] text-[12px]">{name(p)}<button type="button" onClick={()=>setSelected(s=>s.filter(v=>v!==x))}>×</button></span>})}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search teammates" className="flex-1 min-w-[120px] outline-none text-[13px]" /></div><div className="mt-2 max-h-32 overflow-auto rounded-xl border border-[#EAECF0]">{visible.map(p=><button key={id(p)} type="button" onClick={()=>{setSelected(s=>[...s,id(p)]);setQuery("");}} className="block w-full px-3 py-2 text-left text-[13px] hover:bg-[#F5F6FA]">{name(p)} <span className="text-[#9CA3AF]">· {p.role}</span></button>)}</div></div>;
 return <div className="fixed inset-0 z-[60] flex items-center justify-center p-4" onClick={onClose}><div className="absolute inset-0 bg-black/35"/><form onSubmit={e=>{e.preventDefault();save();}} onClick={e=>e.stopPropagation()} className="relative w-full max-w-md max-h-[90vh] overflow-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between mb-5"><div><h2 className="font-bold text-[18px] text-[#111827]">{heading}</h2><p className="text-[12px] text-[#9CA3AF] mt-1">{mode==="event"?"Recipients receive a notification and choose whether to accept.":"Saved to your TeamFlow workspace."}</p></div><button type="button" onClick={onClose}>×</button></div><div className="space-y-3"><div><Label>{mode==="event"?"Meeting title":mode==="groupChat"?"Channel name":mode==="project"?"Project name":"Task title"}</Label><input required autoFocus value={title} onChange={e=>setTitle(e.target.value)} className={field}/></div>{mode!=="groupChat"&&<div><Label>Description</Label><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} className={field}/></div>}{(mode==="task"||mode==="event")&&<div><Label>Project</Label><select value={projectId} onChange={e=>setProjectId(e.target.value)} className={field}>{PROJECTS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>}{mode==="event"&&<Picker/>}{mode==="groupChat"&&<Picker/>}{mode==="task"&&<><div><Label>Assignee</Label><select value={assigneeId} onChange={e=>setAssigneeId(e.target.value)} className={field}>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><select value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="BACKLOG">Backlog</option><option value="IN_PROGRESS">In progress</option><option value="IN_REVIEW">In review</option><option value="DONE">Done</option></select><select value={priority} onChange={e=>setPriority(e.target.value)} className={field}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></div></>}{mode!=="groupChat"&&<div><Label>{mode==="event"?"Start time":"Due date"}</Label><input type={mode==="event"?"datetime-local":"date"} required={mode==="event"} value={startsAt} onChange={e=>setStartsAt(e.target.value)} className={field}/></div>}{mode==="event"&&<div><Label>End time</Label><input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} className={field}/></div>}</div>{error&&<p className="mt-3 text-[12px] text-red-600">{error}</p>}<button disabled={saving} className="w-full mt-5 py-2.5 rounded-xl bg-[#7C5CFC] text-white text-[13px] font-semibold">{saving?"Sending…":mode==="event"?"Send invitation":mode==="groupChat"?"Create channel":"Save"}</button></form></div>;
}
