import mongoose from "mongoose";
import { TeamFlowTaskComment, TeamFlowActivity, TeamFlowChannel, TeamFlowEvent, TeamFlowInvitation, TeamFlowMeetingInvitation, TeamFlowMembership, TeamFlowMessage, TeamFlowNotification, TeamFlowProject, TeamFlowTask, TeamFlowTeamMembership, TeamFlowUser } from "./models.js";

export default function routes(app) {
  const requireUser = (req, res) => req.session.teamFlowUserId || (res.sendStatus(401), null);
  const userFields = "username firstName lastName email role";

  app.post("/api/teamflow/auth/signin", async (req, res) => { const user = await TeamFlowUser.findOne({ username: req.body.username, password: req.body.password }).lean(); if (!user) return res.status(401).json({ message: "Invalid credentials" }); req.session.teamFlowUserId = String(user._id); res.json(user); });
  app.get("/api/teamflow/auth/session", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const user = await TeamFlowUser.findById(userId).select(userFields).lean(); user ? res.json(user) : res.sendStatus(401); });
  app.post("/api/teamflow/auth/signout", (req, res) => req.session.destroy(() => res.sendStatus(204)));
  app.patch("/api/teamflow/auth/profile", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { firstName, lastName, email, currentPassword, newPassword } = req.body; const user = await TeamFlowUser.findById(userId); if (!user) return res.sendStatus(401); if (newPassword) { if (currentPassword !== user.password) return res.status(400).json({ message: "Your current password is incorrect." }); if (String(newPassword).length < 8) return res.status(400).json({ message: "Your new password must be at least 8 characters." }); user.password = newPassword; } if (firstName !== undefined) user.firstName = String(firstName).trim(); if (lastName !== undefined) user.lastName = String(lastName).trim(); if (email !== undefined) { const next = String(email).trim().toLowerCase(); if (!next.includes("@")) return res.status(400).json({ message: "Enter a valid email address." }); user.email = next; } if (!user.firstName || !user.lastName) return res.status(400).json({ message: "First and last name are required." }); await user.save(); res.json({ _id: user._id, username: user.username, firstName: user.firstName, lastName: user.lastName, email: user.email, role: user.role }); });

  app.get("/api/teamflow/notifications", async (req, res) => { const userId = requireUser(req, res); if (userId) res.json(await TeamFlowNotification.find({ user: userId }).populate({ path: "meetingInvitation", populate: { path: "event", select: "title startsAt endsAt" } }).sort({ createdAt: -1 }).limit(20).lean()); });
  app.post("/api/teamflow/notifications/:id/read", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const item = await TeamFlowNotification.findOneAndUpdate({ _id: req.params.id, user: userId }, { read: true }, { new: true }); item ? res.json(item) : res.sendStatus(404); });
  app.post("/api/teamflow/notifications/read-all", async (req, res) => { const userId = requireUser(req, res); if (userId) { await TeamFlowNotification.updateMany({ user: userId, read: false }, { read: true }); res.sendStatus(204); } });

  app.post("/api/teamflow/projects", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { name, description = "", dueDate } = req.body; if (!name?.trim()) return res.status(400).json({ message: "Project name is required" }); const project = await TeamFlowProject.create({ name: name.trim(), description, dueDate: dueDate || undefined, owner: userId, slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}-${Date.now()}`, color: "#7C5CFC" }); await TeamFlowMembership.create({ user: userId, project: project._id, role: "OWNER" }); res.status(201).json(project); });
  app.patch("/api/teamflow/projects/:id", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { status } = req.body; if (!["ON_TRACK", "AT_RISK", "BLOCKED", "COMPLETE", "ARCHIVED"].includes(status)) return res.status(400).json({ message: "Choose a valid project status." }); if (!await TeamFlowMembership.exists({ user: userId, project: req.params.id })) return res.sendStatus(403); const project = await TeamFlowProject.findByIdAndUpdate(req.params.id, { status }, { new: true }); if (!project) return res.sendStatus(404); await TeamFlowActivity.create({ actor: userId, project: project._id, type: "PROJECT_STATUS_CHANGED", message: `changed project status to ${status.replace("_", " ").toLowerCase()}` }); res.json(project); });
  app.post("/api/teamflow/tasks", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { title, description = "", projectId, assigneeId, dueDate, priority = "MEDIUM", status = "BACKLOG" } = req.body; if (!title?.trim() || !projectId) return res.status(400).json({ message: "Task title and project are required" }); if (!await TeamFlowMembership.exists({ user: userId, project: projectId })) return res.sendStatus(403); const assignee = assigneeId || userId; if (!await TeamFlowMembership.exists({ user: assignee, project: projectId })) return res.status(400).json({ message: "Assignee must be a project member" }); const task = await TeamFlowTask.create({ title: title.trim(), description, project: projectId, assignee, dueDate: dueDate || undefined, priority, status }); await TeamFlowActivity.create({ actor: userId, project: projectId, task: task._id, type: "CREATED", message: "created a task" }); res.status(201).json(task); });
  const accessibleTask = async (req, res) => {
    const userId = requireUser(req, res); if (!userId) return null;
    if (!mongoose.isValidObjectId(req.params.id)) { res.sendStatus(404); return null; }
    const task = await TeamFlowTask.findById(req.params.id);
    if (!task || !await TeamFlowMembership.exists({ user: userId, project: task.project })) { res.sendStatus(404); return null; }
    return task;
  };
  const taskHandler = (handler) => async (req, res) => { try { await handler(req, res); } catch (error) { console.error("Task request failed", error.name); res.status(500).json({ message: "Could not complete this request. Please try again." }); } };
  app.get("/api/teamflow/tasks/:id", taskHandler(async (req, res) => {
    const task = await accessibleTask(req, res); if (!task) return;
    const members = await TeamFlowMembership.find({ project: task.project }).populate("user", userFields).lean();
    res.json({ task, members: members.map((item) => item.user).filter(Boolean) });
  }));
  app.patch("/api/teamflow/tasks/:id", taskHandler(async (req, res) => {
    const task = await accessibleTask(req, res); if (!task) return;
    const input = req.body;
    if (input.title !== undefined && (typeof input.title !== "string" || !input.title.trim() || input.title.length > 200)) return res.status(400).json({ message: "Enter a task title of 1–200 characters." });
    if (input.description !== undefined && (typeof input.description !== "string" || input.description.length > 10000)) return res.status(400).json({ message: "Description must be at most 10,000 characters." });
    if (input.status !== undefined && !["BACKLOG", "IN_PROGRESS", "IN_REVIEW", "DONE"].includes(input.status)) return res.status(400).json({ message: "Choose a valid task status." });
    if (input.priority !== undefined && !["LOW", "MEDIUM", "HIGH", "URGENT"].includes(input.priority)) return res.status(400).json({ message: "Choose a valid priority." });
    if (input.dueDate && (typeof input.dueDate !== "string" || !Number.isFinite(Date.parse(input.dueDate)))) return res.status(400).json({ message: "Choose a valid due date." });
    if (input.assigneeId && (!mongoose.isValidObjectId(input.assigneeId) || !await TeamFlowMembership.exists({ project: task.project, user: input.assigneeId }))) return res.status(400).json({ message: "Choose a member of this project." });
    for (const field of ["title", "description", "status", "priority"]) if (input[field] !== undefined) task[field] = field === "title" ? input[field].trim() : input[field];
    if (input.dueDate !== undefined) task.dueDate = input.dueDate || undefined;
    if (input.assigneeId !== undefined) task.assignee = input.assigneeId || undefined;
    await task.save();
    await TeamFlowActivity.create({ actor: req.session.teamFlowUserId, project: task.project, task: task._id, type: "TASK_UPDATED", message: "updated task details" });
    res.json(task);
  }));
  app.get("/api/teamflow/tasks/:id/comments", taskHandler(async (req, res) => {
    const task = await accessibleTask(req, res); if (!task) return;
    res.json(await TeamFlowTaskComment.find({ task: task._id }).populate("author", "firstName lastName").sort({ createdAt: 1 }).lean());
  }));
  app.post("/api/teamflow/tasks/:id/comments", taskHandler(async (req, res) => {
    const task = await accessibleTask(req, res); if (!task) return;
    if (typeof req.body.body !== "string" || !req.body.body.trim() || req.body.body.length > 5000) return res.status(400).json({ message: "Enter a comment of 1–5,000 characters." });
    const comment = await TeamFlowTaskComment.create({ task: task._id, author: req.session.teamFlowUserId, body: req.body.body.trim() });
    await TeamFlowActivity.create({ actor: req.session.teamFlowUserId, project: task.project, task: task._id, type: "TASK_COMMENTED", message: "commented on a task" });
    res.status(201).json(await comment.populate("author", "firstName lastName"));
  }));

  app.post("/api/teamflow/events", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { title, description = "", projectId, startsAt, endsAt, attendeeIds = [], meetingUrl = "" } = req.body; if (!title?.trim() || !projectId || !startsAt) return res.status(400).json({ message: "Title, project, and start time are required" }); if (!await TeamFlowMembership.exists({ user: userId, project: projectId })) return res.sendStatus(403); const invitees = [...new Set(attendeeIds.map(String))].filter((id) => id !== String(userId)); const event = await TeamFlowEvent.create({ title: title.trim(), description, project: projectId, startsAt, endsAt: endsAt || new Date(new Date(startsAt).getTime() + 1800000), attendees: [userId], meetingUrl }); const invitations = await Promise.all(invitees.map((invitee) => TeamFlowMeetingInvitation.create({ event: event._id, invitee, invitedBy: userId }))); if (invitations.length) await TeamFlowNotification.insertMany(invitations.map((item) => ({ user: item.invitee, title: "Meeting invitation", body: `You were invited to ${event.title}.`, meetingInvitation: item._id }))); res.status(201).json({ event, invitationsSent: invitations.length }); });
  app.post("/api/teamflow/meeting-invitations/:id/respond", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const status = req.body.status; if (!["ACCEPTED", "DECLINED"].includes(status)) return res.status(400).json({ message: "Choose Accepted or Declined." }); const invite = await TeamFlowMeetingInvitation.findOne({ _id: req.params.id, invitee: userId, status: "PENDING" }).populate("event"); if (!invite) return res.status(404).json({ message: "This invitation is no longer pending." }); invite.status = status; await invite.save(); if (status === "ACCEPTED") await TeamFlowEvent.findByIdAndUpdate(invite.event._id, { $addToSet: { attendees: userId } }); const person = await TeamFlowUser.findById(userId).select("firstName lastName").lean(); await TeamFlowNotification.create({ user: invite.invitedBy, title: `Meeting ${status.toLowerCase()}`, body: `${person.firstName} ${person.lastName} ${status === "ACCEPTED" ? "accepted" : "declined"} ${invite.event.title}.`, link: "/Kanbas/Calendar" }); await TeamFlowNotification.updateMany({ user: userId, meetingInvitation: invite._id }, { read: true }); res.json(invite); });

  const commonTeam = async (userId, ids = []) => { const teams = await TeamFlowTeamMembership.find({ user: userId }).select("team").lean(); for (const { team } of teams) if (await TeamFlowTeamMembership.countDocuments({ team, user: { $in: [userId, ...ids] } }) === new Set([userId, ...ids].map(String)).size) return team; return null; };
  app.get("/api/teamflow/people", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const own = await TeamFlowTeamMembership.find({ user: userId }).select("team").lean(), teamIds = own.map(({ team }) => team), search = String(req.query.search || "").trim(); if (search) { const rx = new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"), users = await TeamFlowUser.find({ $or: [{ firstName: rx }, { lastName: rx }, { email: rx }, { username: rx }] }).select("firstName lastName email role").limit(20).lean(), memberships = await TeamFlowTeamMembership.find({ user: { $in: users.map((u) => u._id) }, team: { $in: teamIds } }).populate("team", "name").lean(), byUser = new Map(memberships.map(({ user, team }) => [String(user), team?.name || "Your team"])); return res.json(users.map((u) => ({ ...u, team: byUser.get(String(u._id)) || "Other workspace member" }))); } const memberships = await TeamFlowTeamMembership.find({ team: { $in: teamIds } }).populate("user", "firstName lastName email role").populate("team", "name").lean(); res.json(Array.from(new Map(memberships.map(({ user, team }) => [user?._id?.toString(), { ...user, team: team?.name || "Team" }]).filter(([id]) => id)).values())); });
  app.get("/api/teamflow/channels", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const channels = await TeamFlowChannel.find({ members: userId }).populate("members", "firstName lastName email role").sort({ updatedAt: -1 }).lean(), ids = channels.map((c) => c._id), latest = await TeamFlowMessage.aggregate([{ $match: { channel: { $in: ids } } }, { $sort: { createdAt: -1 } }, { $group: { _id: "$channel", body: { $first: "$body" }, createdAt: { $first: "$createdAt" }, sender: { $first: "$sender" } } }]), byId = new Map(latest.map((m) => [String(m._id), m])); res.json(channels.map((c) => ({ ...c, latest: byId.get(String(c._id)) || null }))); });
  app.post("/api/teamflow/channels/direct", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const memberId = req.body.memberId; if (!memberId || String(memberId) === String(userId)) return res.status(400).json({ message: "Choose another teammate." }); const team = await commonTeam(userId, [memberId]); if (!team) return res.sendStatus(403); let channel = await TeamFlowChannel.findOne({ team, type: "DIRECT", members: { $all: [userId, memberId] }, $expr: { $eq: [{ $size: "$members" }, 2] } }); if (!channel) channel = await TeamFlowChannel.create({ team, type: "DIRECT", members: [userId, memberId], createdBy: userId }); res.status(201).json(await channel.populate("members", "firstName lastName email role")); });
  app.post("/api/teamflow/channels/group", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const { name, memberIds = [] } = req.body; if (!name?.trim() || !memberIds.length) return res.status(400).json({ message: "A channel name and at least one teammate are required." }); const members = [...new Set([userId, ...memberIds].map(String))], team = await commonTeam(userId, members.filter((id) => id !== String(userId))); if (!team) return res.sendStatus(403); const channel = await TeamFlowChannel.create({ team, type: "GROUP", name: name.trim(), members, createdBy: userId }); res.status(201).json(await channel.populate("members", "firstName lastName email role")); });
  app.get("/api/teamflow/channels/:id/messages", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; if (!await TeamFlowChannel.exists({ _id: req.params.id, members: userId })) return res.sendStatus(404); res.json(await TeamFlowMessage.find({ channel: req.params.id }).populate("sender", "firstName lastName").sort({ createdAt: 1 }).limit(100).lean()); });
  app.get("/api/teamflow/workspace", async (req, res) => { const userId = requireUser(req, res); if (!userId) return; const [currentUser, memberships] = await Promise.all([TeamFlowUser.findById(userId).select("firstName lastName email role").lean(), TeamFlowMembership.find({ user: userId }).populate("project").lean()]), projects = memberships.map(({ project }) => project).filter(Boolean), ids = projects.map((p) => p._id), [tasks, events, activity, workspaceMemberships] = await Promise.all([TeamFlowTask.find({ project: { $in: ids } }).populate("assignee", "firstName lastName role").populate("project", "name slug color").sort({ dueDate: 1 }).lean(), TeamFlowEvent.find({ project: { $in: ids }, attendees: userId }).populate("project", "name color").populate("attendees", "firstName lastName role").sort({ startsAt: 1 }).lean(), TeamFlowActivity.find({ project: { $in: ids } }).populate("actor", "firstName lastName").populate("project", "name color").populate("task", "title").sort({ createdAt: -1 }).limit(30).lean(), TeamFlowMembership.find({ project: { $in: ids } }).populate("user", "firstName lastName role email").lean()]); const members = Array.from(new Map(workspaceMemberships.map(({ user }) => [user?._id?.toString(), user]).filter(([id]) => id)).values()); res.json({ currentUser, projects, members, tasks, events, activity }); });
}
